#!/usr/bin/env node
/*
 * MIT License
 * 
 * Copyright (c) 2026 EgEhE
 * 
 */

/**
 * Automatically adjusts pivot points in panto.js based on .bbmodel origins
 * and generates 2-link inverse kinematics for pantograph arms.
 * 
 * Usage: node pivotfix.js model.bbmodel panto.js [output.js]
 */

const fs = require("fs");

function fail(msg) {
	console.error("ERROR: " + msg);
	process.exit(1);
}

const [, , bbPath, jsPath, outPathArg] = process.argv;

if (!bbPath || !jsPath) {
	console.log("Usage: node pivotfix.js model.bbmodel panto.js [output.js]");
	process.exit(1);
}

if (!fs.existsSync(bbPath)) fail(`.bbmodel not found: ${bbPath}`);
if (!fs.existsSync(jsPath)) fail(`.js not found: ${jsPath}`);

const outPath = outPathArg || jsPath;
const SCALE = 16; // Blockbench scale (16 units = 1 meter)

// 1. Read group origins from bbmodel
const bb = JSON.parse(fs.readFileSync(bbPath, "utf8"));

const originByGroup = new Map();
for (const g of bb.groups || []) {
	if (originByGroup.has(g.name)) {
		console.warn(`WARNING: duplicate group "${g.name}", keeping first.`);
		continue;
	}
	originByGroup.set(g.name, g.origin);
}

if (originByGroup.size === 0) fail("No groups found in the bbmodel.");

console.log("Group pivots read from bbmodel (meters):");
for (const [name, [, oy, oz]] of originByGroup) {
	console.log(`  ${name}: y=${(oy / SCALE).toFixed(5)}  z=${(oz / SCALE).toFixed(5)}`);
}

function fmt(n) {
	if (Math.abs(n) < 1e-9) return "0";
	let s = n.toFixed(5);
	return s.replace(/0+$/, "").replace(/\.$/, "");
}

// 2. Patch pivot blocks in js file
const jsText = fs.readFileSync(jsPath, "utf8");

const pivotBlockRe =
	/matrices\.translate\(\s*0\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\);\s*matrices\.rotateX\([^;]*\);\s*matrices\.translate\(\s*0\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\);\s*if\s*\(\s*pantoModels\[\s*["'](\w+)["']\s*\]\s*\)/g;

function replaceInOrder(text, pairs) {
	let result = "";
	let cursor = 0;
	for (const [oldVal, newVal] of pairs) {
		const idx = text.indexOf(oldVal, cursor);
		if (idx === -1) return null;
		result += text.slice(cursor, idx) + newVal;
		cursor = idx + oldVal.length;
	}
	result += text.slice(cursor);
	return result;
}

let foundCount = 0;
let changedCount = 0;
const notFoundParts = [];

const newJsText = jsText.replace(
	pivotBlockRe,
	(match, y1, z1, y2, z2, partName) => {
		foundCount++;

		const origin = originByGroup.get(partName);
		if (!origin) {
			notFoundParts.push(partName);
			return match;
		}

		const [, oy, oz] = origin;
		const newY = fmt(oy / SCALE);
		const newZ = fmt(oz / SCALE);
		const newYNeg = fmt(-oy / SCALE);
		const newZNeg = fmt(-oz / SCALE);

		if (y1 === newY && z1 === newZ && y2 === newYNeg && z2 === newZNeg) {
			console.log(`"${partName}": up to date, no change.`);
			return match;
		}

		console.log(`"${partName}": updated pivot bounds.`);
		changedCount++;

		const patched = replaceInOrder(match, [
			[y1, newY],
			[z1, newZ],
			[y2, newYNeg],
			[z2, newZNeg],
		]);

		return patched ?? match;
	}
);

if (foundCount === 0) {
	fail("No matching pivot block found in the JS file.");
}

if (notFoundParts.length > 0) {
	console.warn(`WARNING: parts missing in bbmodel: ${notFoundParts.join(", ")}`);
}

console.log(`\nUpdated ${changedCount} of ${foundCount} pivot block(s).`);

// 3. Update Inverse Kinematics calculation
const BASE_PART = "p1";
const ELBOW_PART = "p2";
const TIP_PART = "p3";

function reqOrigin(name) {
	const o = originByGroup.get(name);
	if (!o) fail(`Group "${name}" required for IK calculation not found.`);
	return { y: o[1] / SCALE, z: o[2] / SCALE };
}

const baseP = reqOrigin(BASE_PART);
const elbowP = reqOrigin(ELBOW_PART);
const tipP = reqOrigin(TIP_PART);

const l1 = Math.hypot(elbowP.z - baseP.z, elbowP.y - baseP.y);
const l2 = Math.hypot(tipP.z - elbowP.z, tipP.y - elbowP.y);
const baseAngle1 = Math.atan2(elbowP.y - baseP.y, elbowP.z - baseP.z);
const restAngle2Abs = Math.atan2(tipP.y - elbowP.y, tipP.z - elbowP.z);
const restTheta2 = restAngle2Abs - baseAngle1;

const IK_BEGIN = "// --- REAL 2-LINK INVERSE KINEMATICS START (auto-generated by pivotfix.js, do not edit by hand) ---";
const IK_END = "// --- REAL 2-LINK INVERSE KINEMATICS END ---";

function buildIkBlock(indent) {
	return [
		`${indent}${IK_BEGIN}`,
		`${indent}const pantoL1 = ${fmt(l1)};`,
		`${indent}const pantoL2 = ${fmt(l2)};`,
		`${indent}const pantoBaseAngle1 = ${fmt(baseAngle1)};`,
		`${indent}const pantoRestTheta2 = ${fmt(restTheta2)};`,
		`${indent}let pantoAngle1 = 0, pantoAngle2 = 0;`,
		`${indent}{`,
		`${indent}    let ik = tryFind2dInverseKinematicsPanto(${fmt(baseP.z)}, ${fmt(baseP.y)}, ${fmt(tipP.z)}, currentHeight, pantoL1, pantoL2);`,
		`${indent}    if (ik) {`,
		`${indent}        let v = (Math.sign(ik[0].theta2) === Math.sign(pantoRestTheta2)) ? ik[0] : ik[1];`,
		`${indent}        pantoAngle1 = -(v.theta1 - pantoBaseAngle1);`,
		`${indent}        pantoAngle2 = -(v.theta2 - pantoRestTheta2);`,
		`${indent}    }`,
		`${indent}}`,
		`${indent}${IK_END}`,
	].join("\n");
}

const markerRe = new RegExp(
	`([ \\t]*)${IK_BEGIN.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${IK_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`
);

const oldFormulaRe =
	/([ \t]*)let ratio = \(currentHeight[\s\S]*?let pantoAngle2 = -deltaAngle \* 2;/;

let finalJsText;
if (markerRe.test(newJsText)) {
	finalJsText = newJsText.replace(markerRe, (match, indent) => buildIkBlock(indent));
	console.log("Updated existing inverse kinematics block.");
} else if (oldFormulaRe.test(newJsText)) {
	finalJsText = newJsText.replace(oldFormulaRe, (match, indent) => buildIkBlock(indent));
	console.log("Replaced legacy inverse kinematics formula.");
} else {
	console.warn("WARNING: Inverse kinematics insertion point not found.");
	finalJsText = newJsText;
}

// 4. Write result
if (!outPathArg) {
	const backupPath = jsPath + ".bak";
	fs.copyFileSync(jsPath, backupPath);
	console.log(`Backup created: ${backupPath}`);
}

fs.writeFileSync(outPath, finalJsText, "utf8");
console.log(`Written: ${outPath}`);